artifats_root:

data_ingestion: 
  dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1pfIAlurfeqFTbirUZ5v_vapIoGPgRiXY/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_data: aratifacts/data