artifacts_root: artifacts

data_ingestion:
  dir: artifacts/data_ingestion 
  source_url: https://drive.google.com/file/d/1pfIAlurfeqFTbirUZ5v_vapIoGPgRiXY/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

custom_model:
  dir: artifacts/custom_model
  custom_model_path: artifacts/custom_model/model.h5

model_train:
  dir: artifcts/model_train
  model: artifacts/custom_model/model.h5
  model_path: artifacts/model_train/model.h5
  